### ISSUE TITLE
Execution failed for task ':configureChromeDriverBinary'.

### ISSUE THREAD

**Issue by tseveen-ai** [graceframework/grace-framework#258]
### Expected Behavior

An error occurred when creating a new project and running the "gradlew build" command. 

![image](https://github.com/graceframework/grace-framework/assets/138235535/ce96449c-51ba-422b-8e87-648060587bbc)

### Actual Behaviour

chromedriver version upgrade to '122.0.6260.0' and geckodriver version downgrade to '0.33.0' worked fine.

![image](https://github.com/graceframework/grace-framework/assets/138235535/2cf70349-139c-4348-b3a0-cf8360a02f38)

### Environment Information

![image](https://github.com/graceframework/grace-framework/assets/138235535/39f93317-b04b-4350-8e84-ce7473c6018b)

### Version

Grace 2023.0.0-M5

**Comment by rainboyan** [comment]
@tseveend Thanks for the report, this is my carelessness, maybe I just upgraded the version and forgot to verify.

you can set `chromedriver.version` to `122.0.6260.0`, chromedriver always upgrades too fast to keep up with the latest version.

```gradle
webdriverBinaries {
    chromedriver {
        version = '122.0.6260.0'
        fallbackTo32Bit = true
    }
    geckodriver '0.33.0'
}
```

The other solution is to do what is said [here](https://github.com/erdi/webdriver-binaries-gradle-plugin#configuring-download-urls).

**Comment by rainboyan** [comment]
Fixed in https://github.com/grace-profiles/base/commit/ef373d9ea24503af749560dd09eb156b27cc7380
