### ISSUE TITLE
Compiled class is created in the wrong folder

### ISSUE THREAD

**Issue by tseveen-ai** [graceframework/grace-framework#259]
### Expected Behavior

Compiled class is created in the wrong folder(in src/main folder) when changing java or groovy code while the application runs in "gradlew bootRun". This works correctly if the package name is single. The following error occurs when the package name consists of multiple dots.

![image](https://github.com/graceframework/grace-framework/assets/138235535/6945af5b-d530-447d-94a4-ecd8e0254965)

project source [hello.zip](https://github.com/graceframework/grace-framework/files/14882052/hello.zip)

### Environment Information

![image](https://github.com/graceframework/grace-framework/assets/138235535/ebb838f2-775c-4866-b8a8-1b4838a22d24)

### Version

Grace 2023.0.0-M5

**Comment by rainboyan** [comment]
@tseveend Thanks for your report. It will be fixed in the next milestone.
