### ISSUE TITLE
Explicitly set resolve strategy to `OWNER_FIRST` in `BeanBuilder.invokeBeanDefiningClosure`

### ISSUE THREAD

**Issue by tseveen-ai** [graceframework/grace-framework#269]
Grails plugin an error occur when doWithSpring is executed.

![image](https://github.com/graceframework/grace-framework/assets/138235535/4fe9ad02-4654-409f-a859-03fedc311aaf)

https://github.com/graceframework/grace-framework/blob/e1e9233e238e7274f8ac6c11dd2db320bb05b99b/grails-plugin-api/src/main/groovy/org/grails/plugins/DefaultGrailsPlugin.java#L578

**Comment by rainboyan** [comment]
@tseveend Thanks for your report.
I created a demo [here](https://github.com/grace-issues/gh-issue-269) to reproduce the error, but I don't see any error, can you give some details about it?

**Comment by tseveen-ai** [comment]
@rainboyan I created and attached a demo with the issue. Thank you for your quick response

[demo.zip](https://github.com/graceframework/grace-framework/files/14898168/demo.zip)

![image](https://github.com/graceframework/grace-framework/assets/138235535/fc3dba63-33a7-4645-a261-ef31fcd4afa5)

**Comment by rainboyan** [comment]
@tseveend Thank you for the demo.

I can confirm that the relevant code that causes the error is as follows:

https://github.com/graceframework/grace-framework/blob/e1e9233e238e7274f8ac6c11dd2db320bb05b99b/grails-spring/src/main/groovy/grails/spring/BeanBuilder.java#L657-L664

According to the [Closures Delegation strategy](http://docs.groovy-lang.org/docs/groovy-4.0.11/html/documentation/#_delegation_strategy_2), the default Delegation strategy is `Closure.OWNER_FIRST`, but in fact it doesn't work the same in Groovy 3 and Groovy 4. In Groovy 4, we should set it explicitly. Maybe this is a bug in Groovy 4.

> * Closure.OWNER_FIRST is the default strategy. If a property/method exists on the owner, then it will be called on the owner. If not, then the delegate is used.
> * Closure.DELEGATE_FIRST reverses the logic: the delegate is used first, then the owner

**Comment by rainboyan** [comment]
I wrote a Groovy script to reproduce the issue. I'm not sure if this is a bug from Groovy 3 or Groovy 4, but the result is different when this code is executed in the `GroovyConsole`, and I need to check with the Groovy developers. Also, I'll fix this in Grace.

```groovy
class Plugin {

    Closure doWithSpring() { {->
            Properties properties = loadProperties()
            println properties
        }
    }

    def loadProperties() {
        Properties properties = new Properties()
        properties['foo'] = 'Foo'
        properties
    }

}

class BeanBuilder {

    BeanBuilder beans(Closure<?> callable) {
        callable.setDelegate(this)
        // Groovy 4 should set it explicitly
        callable.setResolveStrategy(Closure.OWNER_FIRST)
        callable.call()
        return this
    }

    @Override
    public Object invokeMethod(String name, Object arg) {
        println "BeanBuilder.invokeMethod($name, $arg)"
        return this
    }
}

BeanBuilder bb = new BeanBuilder()
Plugin plugin = new Plugin()

Closure c = plugin.doWithSpring()
c.setDelegate(bb)
c.setResolveStrategy(Closure.DELEGATE_FIRST)

bb.beans(c)
```

**Comment by rainboyan** [comment]
@tseveend 

I reopened this issue because some tests fail, `DynamicPlugin` has its own `invokeMethod()`, it may conflict with `BeanBuilder. invokeMethod `.

I recommend using Spring `AutoConfiguration`, it's better than `Plugin.doWithSpring()`.
