### ISSUE TITLE
i18n/messages.properties error

### ISSUE THREAD

**Issue by tseveen-ai** [graceframework/grace-framework#289]
### Describe the bug

create a project, and modify the "i18n/messages.properties" file, I get the following error. 

![image](https://github.com/graceframework/grace-framework/assets/138235535/fee5bc2e-0ab2-4eeb-9d8e-49c44579ffb9)

### How to Reproduce?

Works fine to change the code "File eventFile = event.source.getFile().canonicalFile" instead of "File eventFile = event.source.file.canonicalFile"
on I18nGrailsPlugin.groovy:82

### Grace version (ie. output of `grace -v`)

![image](https://github.com/graceframework/grace-framework/assets/138235535/ed62713f-ed56-4424-9083-6996209d16be)

**Comment by rainboyan** [comment]
@tseveend Thank you for your report.
