### ISSUE TITLE
2023.0.x Default Behavior of Asset Pipeline should be skipNonDigests = true

### ISSUE THREAD

**Issue by codeconsole** [graceframework/grace-framework#442]
### Issue description

Duplicate exact assets are being bundled into the jar which result in an unnecessarily larger file size:

```
72M Aug  8 00:53 website-0.0.1-SNAPSHOT.jar
69M Aug  8 00:57 website-0.0.1-SNAPSHOT-skipNonDigests.jar
```

This is due to `skipNonDigests` being false.

Setting
```
assets {
    skipNonDigests = true
}
```
results in the [example app](https://github.com/codeconsole/grace-website) being `3M` smaller

For instance
```
% unzip -l website-0.0.1-SNAPSHOT.jar|grep bootstrap-icons
    96020  08-08-2024 05:53   assets/bootstrap-icons.css
   130338  08-08-2024 05:53   assets/bootstrap-icons.woff2.gz
    13711  08-08-2024 05:53   assets/bootstrap-icons.min-ef7d2e93cd565b90163303233b75d579.css.gz
   130396  08-08-2024 05:53   assets/bootstrap-icons-cc1e5eda776be5f0ff614285c31d4892.woff2
   175175  08-08-2024 05:53   assets/bootstrap-icons.woff.gz
    13807  08-08-2024 05:53   assets/bootstrap-icons.css.gz
    96020  08-08-2024 05:53   assets/bootstrap-icons-b9f4efb47bc1b812a2b369ccd4ca838c.css
   176032  08-08-2024 05:53   assets/bootstrap-icons-ba49e844892321d8540ea3b7c088cf97.woff
    13807  08-08-2024 05:53   assets/bootstrap-icons-b9f4efb47bc1b812a2b369ccd4ca838c.css.gz
    85930  08-08-2024 05:53   assets/bootstrap-icons.min.css
   175175  08-08-2024 05:53   assets/bootstrap-icons-ba49e844892321d8540ea3b7c088cf97.woff.gz
   130338  08-08-2024 05:53   assets/bootstrap-icons-cc1e5eda776be5f0ff614285c31d4892.woff2.gz
   130396  08-08-2024 05:53   assets/bootstrap-icons.woff2
    13711  08-08-2024 05:53   assets/bootstrap-icons.min.css.gz
    85930  08-08-2024 05:53   assets/bootstrap-icons.min-ef7d2e93cd565b90163303233b75d579.css
   176032  08-08-2024 05:53   assets/bootstrap-icons.woff
```
`assets/bootstrap-icons.css` and `assets/bootstrap-icons-b9f4efb47bc1b812a2b369ccd4ca838c.css` are identical and so are `assets/bootstrap-icons.woff` and `assets/bootstrap-icons-ba49e844892321d8540ea3b7c088cf97.woff` etc.

**Comment by rainboyan** [comment]
@codeconsole Thanks for your report.

> By default both digested named versions of assets as well as non digested named versions are generated as well as the gzip equivalents. Some frameworks dont actually need the non digested named versions ( `ratpack`, `grails`, `spring-boot`, and `servlets`). These frameworks take advantage of the `manifest.properties` file discussed earlier in the documentation to properly map requests for non digested file names to the digested equivalent and preserve compatibility with libraries that may not work well with digested file names.

This issue is closed via https://github.com/grace-profiles/base/commit/bd220429dbc1ccc868d4d900512b90e96fc98dc0

**Comment by codeconsole** [comment]
I don't think default behavior should be part of the generated app.  It is confusing to new developers and implies it is not default behavior. 

The following should be removed and could be replaced with a link to a code block with defaults.
```
// https://github.com/grace-plugins/grace-asset-pipeline?tab=readme-ov-file
```

```gradle
assets {
    minifyJs = true
    minifyCss = true
}
```

Furthermore, I think `skipNonDigests = true` should be a [default of the plugin](https://github.com/grace-plugins/grace-asset-pipeline?tab=readme-ov-file)
